project_name: go-cti
release:
  github:
    owner: vulsio
    name: go-cti
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
- id: linux-amd64
  goos:
    - linux
  goarch:
    - amd64
  env:
    - CC=x86_64-linux-gnu-gcc
  main: .
  ldflags: -s -w -X github.com/vulsio/go-cti/config.Version={{.Version}} -X github.com/vulsio/go-cti/config.Revision={{.Commit}}
  binary: go-cti
- id: linux-arm64
  goos:
    - linux
  goarch:
    - arm64
  env:
    - CC=aarch64-linux-gnu-gcc
  main: .
  ldflags: -s -w -X github.com/vulsio/go-cti/config.Version={{.Version}} -X github.com/vulsio/go-cti/config.Revision={{.Commit}}
  binary: go-cti
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}